server:
  port: 9092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bankaccountdb
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate: 
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/bankaccountdb?createDatabaseIfNotExist=true
    username: root
    password: sql

security:
  oauth2:
    resource:
      jwt:
        key-value: bankSecretKey
